# NUMPY

# >>>>>>>>>>>>>>>>>>>>>DAY 01

 ## Syllabus

In [7]:
# Introduction To Numpy
# Creating Multi-Dimensional Numpy Arrays
# Arange Function
# Zeros, Ones and Eye functions
# Reshape Function
# Linspace
# Resize Function
# Random.rand
# Random.randn
# Random.randint
# Indexing & Slicing
# Broadcasting
# How To Create A Copy Dataset
# DataFrame Introduction
# Creating Matrix

In [16]:
# List vs array

In [17]:
a1 = [1,2,3,4,5,6,7,8,9,10]

In [25]:
print(2*a1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


# for doing elemnt wise operation 

In [18]:
for i in a1:
    print(2*i)

2
4
6
8
10
12
14
16
18
20


In [23]:
print([i*2 for i in a1])

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [24]:
arr1 = np.array(a1)

In [26]:
print(2*arr1)

[ 2  4  6  8 10 12 14 16 18 20]


# for doing foaster operations

In [33]:
i = range(10000)


In [34]:
%timeit [i*2 for i in a1]

583 ns ± 14.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [35]:
i =  np.arange(1000)

In [36]:
%timeit (i*2)

2.02 µs ± 60.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# IMP Attributes

In [42]:
arr2 = np.array(a1)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]


In [44]:
print(arr2.ndim)

1


In [45]:
print(arr2.shape)

(10,)


In [46]:
print(arr2.size)

10


In [47]:
print(arr2.dtype)

int32


In [48]:
print(arr2.itemsize) #32/8 = 4

4


# Array Creation 

In [50]:
print(np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [51]:
print(np.arange(15,50)) # range

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49]


In [52]:
print(np.arange(15,50,10)) #step size

[15 25 35 45]


In [54]:
print(np.linspace(1,10,20)) #lin space

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


# Data Types in NUMPY

In [234]:
#  converting to homogenous data type in an array

In [57]:
arr2 = [1,2,3,4,5,6,7,8,9,10]
print(arr2)
arr3 = [1.1,2,3,4,5,6,7,8,9,10]
print(arr3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1.1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [62]:
print(np.array([arr2]))
print(np.array([arr3])) # every element is converted into float to maintain homogeniety

[[ 1  2  3  4  5  6  7  8  9 10]]
[[ 1.1  2.   3.   4.   5.   6.   7.   8.   9.  10. ]]


In [64]:
arr4 = [1,2,3,4,5,6,7,8,9,'10']
print(np.array([arr4]))

[['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']]


# 2D Array

In [66]:
m = ([[1,1,1],[2,2,2]])
print(m)

[[1, 1, 1], [2, 2, 2]]


In [68]:
m1 = np.array(m)
print(m1)
print(m1.ndim)
print(m1.size)
print(m1.shape)


[[1 1 1]
 [2 2 2]]
2
6
(2, 3)


In [69]:
m1.reshape(6,1) #column vecort

array([[1],
       [1],
       [1],
       [2],
       [2],
       [2]])

In [70]:
m1.reshape(1,6) # row vector

array([[1, 1, 1, 2, 2, 2]])

In [71]:
# Easy way of creating 2d array  using reshape

In [72]:
m3 = np.arange(15)
print(m3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [73]:
print(m3.reshape(3,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [74]:
print(m3.reshape(5,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [75]:
# flatten 2d array

In [77]:
print(m3.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [78]:
print(m3.reshape(5,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [82]:
print(m3.reshape(5,-5)) # -5 will be replaced by 3 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


# Initial Placeholders

In [85]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [86]:
print(np.zeros([4,3])) #2d array

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [87]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [88]:
print(np.ones([6,3]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [89]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [90]:
print(np.diag([5,6,7]))

[[5 0 0]
 [0 6 0]
 [0 0 7]]


In [91]:
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Indexing and slicing 

In [114]:
m5 = np.arange(15)
print(m5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [115]:
print(m5[2])

2


In [116]:
print(m5[11])

11


In [117]:
print(m5[[0,2,4]])

[0 2 4]


In [118]:
m5 = np.arange(15).reshape([5,3])
print(m5)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [100]:
print(m5[0][1])

1


In [101]:
print(m5[2][2]) 

8


In [103]:
print(m5[2,2]) # easier notation to access the element  

8


In [124]:
print(m5[[2,2,0],[1,2,2]]) # accessing multiple iteams in a 2D aray

[7 8 2]


# Slicing

In [126]:
arr1 = np.arange(12).reshape(3,4)

In [127]:
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [128]:
print(arr1[0 ,0])

0


In [129]:
print(arr1[0 ,0:2])

[0 1]


In [130]:
print(arr1[2 ,0:])

[ 8  9 10 11]


In [137]:
print(arr1[: ,2:])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [138]:
# reversing array

In [144]:
x = np.array([1,1,1,1,1,1,1])
y = np.array([2,3,4])
x[4:] = y[::-1]
print(x)

[1 1 1 1 4 3 2]


# Indexing with Boolean Arrays

In [145]:
# Masking
# fancy indexing


In [146]:
arr1 = np.arange(12).reshape(3,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [147]:
print(arr1 > 5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [148]:
print(arr1[arr1 > 5]) #filtering the values using masks

[ 6  7  8  9 10 11]


In [149]:
print(arr1[arr1 % 2== 0]) 

[ 0  2  4  6  8 10]


In [150]:
print(arr1[arr1 % 3== 0])

[0 3 6 9]


In [155]:
print(arr1[(arr1 % 2== 0) | (arr1 % 3== 0)]) #multiple conditions

[ 0  2  3  4  6  8  9 10]


In [156]:
arr1 = np.arange(12).reshape(3,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [157]:
ans  = (arr1 % 2 == 0)

In [158]:
arr1[ans] = 100
print(arr1)

[[100   1 100   3]
 [100   5 100   7]
 [100   9 100  11]]


# >>>>>>>>>>>>>>>>>>>>>DAY 02

# Universal Functions

In [168]:
 a = np.array([11,22,33,44,55])
 b = np.array([1,2,3,4,5])    

In [169]:
print(a+b) #np.add(a,b)

[12 24 36 48 60]


In [163]:
print(a-b)

[10 20 30 40 50]


In [164]:
print(a*b)

[ 11  44  99 176 275]


In [165]:
print(a/b)

[11. 11. 11. 11. 11.]


# Aggreagte Function

In [170]:
print(np.sum(a))

165


In [171]:
print(np.sum(b))

15


In [175]:
arr5 = np.arange(10,60,2).reshape(5,5)

In [177]:
print(arr5)

[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]]


In [178]:
print(np.sum(arr5 , axis=0))

[150 160 170 180 190]


In [179]:
print(np.sum(arr5 , axis=1))

[ 70 120 170 220 270]


In [181]:
print(np.mean(arr5))

34.0


In [183]:
print(np.mean(arr5 , axis=0))

[30. 32. 34. 36. 38.]


In [184]:
print(np.mean(arr5 , axis=1))

[14. 24. 34. 44. 54.]


In [186]:
print(np.min(arr5)) 

10


In [187]:
print(np.min(arr5,axis=0)) 

[10 12 14 16 18]


In [188]:
print(np.min(arr5,axis=1))

[10 20 30 40 50]


# Logical Fun

In [192]:
# any = all elements have to be ZERO
a = np.array([11,22,33,44,55])
np.any(a)

True

In [190]:
a = np.array([11,22,33,44,55,0])
np.any(a)

True

In [191]:
a = np.array([0,0,0,0,0])
np.any(a)

False

In [193]:
a1 = np.array([77,8,88,99,6,5])
a2 = np.array([66,8,88,99,6,5])

In [194]:
print(a1>a2)

[ True False False False False False]


In [195]:
print(np.any(a1>a2))

True


In [196]:
print(np.all(a1>a2))

False


In [197]:
print(np.all(a1<a2))

False


In [198]:
a = np.array([11,22,33,44,55,0])
np.sort(a)

array([ 0, 11, 22, 33, 44, 55])

In [199]:
np.argsort(a) #index of sorted array

array([5, 0, 1, 2, 3, 4], dtype=int64)

In [200]:
# sorting in a 2d Array


In [207]:
a = np.array([[12,33,33,44,87,14],[12,44,55,77,44,11],[1,2,3,4,5,6]])

In [208]:
print(a)

[[12 33 33 44 87 14]
 [12 44 55 77 44 11]
 [ 1  2  3  4  5  6]]


In [210]:
print(np.sort(a)) #default sort is last axis , here is axis = 1

[[12 14 33 33 44 87]
 [11 12 44 44 55 77]
 [ 1  2  3  4  5  6]]


# Broadcasting

In [211]:
x = np.array([10,20,30])
y = np.array([[1],[2],[3],[4]])

In [214]:
print(x)
print(x.ndim)
print(x.shape)

[10 20 30]
1
(3,)


In [215]:
print(y)
print(y.ndim)
print(y.shape)

[[1]
 [2]
 [3]
 [4]]
2
(4, 1)


In [217]:
print(x+y)

[[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]]


# Splitting

In [220]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [221]:
print(np.split(x,3))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [223]:
# print(np.split(x,5)) # Error

In [224]:
x = np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [226]:
print(np.split(x,4)) #default axis = 0

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [230]:
print(np.vsplit(x,4))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [227]:
print(np.split(x,4,axis=1)) 

[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [229]:
print(np.hsplit(x ,4))

[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [233]:
# Merging of arrays

# Copies and Views

In [231]:

# No Copy at All
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a            # no new object is created
print(b is a)     # a and b are two names for the same ndarray object
# View or Shallow Copy
c = a.view()
print(c is a)
print(c.base is a  )          # c is a view of the data owned by a
print(c.flags.owndata)
c = c.reshape((2, 6))  # a's shape doesn't change
print(a.shape)
c[0, 4] = 1234         # a's data changes
print(a)

# Deep Copy
d = a.copy()  # a new array object with new data is created
print(d is a)


True
False
True
False
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
False
